; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2 on 2026-04-26 at 14:34:21
; total layer number: 5
; filament_density: 1.04
; filament_diameter: 1.75
; max_z_height: 1.00
; filament: 1
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 928
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAACfklEQVR4Ae2Y20pbQRiFB7ENSRCTxq
; QxB7MTSwulpaFQSgstKbmwhWJD7clKS1Iq1LZCPIGKQcWzohFEwas8Qh7BR8gj5BHyCGN+YSBuNdnz
; 79l7JpAF68abrDVrvkE2IR3drN706zy4y+X0kHYSBA5O/CoPnh5QcGjm71m3745G2kHO+4OpeHGjxs
; Izw996XjzLEpXV9yVT1AfXO5AdLSl3pRzRcDK2uVRtFZ45sjRTcScfZYgK8r4fWjYaXH+lpAIOPwwn
; iQnfaCmAA4xmg1+3BrFDAKHI8Po1LLtSvKCaWUM44FhQzRieZNNrwKmLABVr+G3IQDACqGQF118pbs
; Dr85VUCN/oQO572XiBbx8rA+uLNHGyp0T48EKeeoffVQ0X8H36UAn+ydHw7H+aONqWFjxxvEvvjv+k
; faMjuALg/n+/Kaxhd/jo6vxFcGZ0AeaLNWy6UqGpiUvhhRRga2i7K5YF1/bXANYr4YUVYI4W5oSvAa
; BeF9ySAmCYOX64KeTUGai2FhABeKQw2zK4pQUuAc7x3MLz2D85bji85QXYGrGtQsvwsZ1l6v/xlSu8
; LQWYI4vTNwIenpvkDm57AQZ443Pb7HlUskAj4DygKlWAWUT4ToFOgU4BzgI9L58XVSvgfvqkSHh0Ox
; RMBXJjNRUK3Ar4UwSj+jfLZO+bVyVZBepfI8663C6NmJXr8cM8dg1seOeDe2K/lcIaGLh5g3vepivd
; Xg/uY5YR8QJuKahYwRr+sc9VUQV8I8M1NKhmZARwI6ASmXJoA5lmgDcL74jHskQFwZXyDKXLRgvAqV
; sKKlYAuH4NaaBipQdcOqhYMcCVABUr+H+qrU5dhs4BPjqA/djqShwAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 4852
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAN/UlEQVR4Ae3c4Y5dVR2G8QPBEorIQK
; EMLaUtGA0GY2M0igmkph/AxAAJqEGiKUSCVdEqEJRAilFAMVqN0cRPXAKXwCX0EnoJXMLIGufUM9OZ
; OfvsWXvv9V/r9yTPFzV+ma4367xZ757NAAAAAAAAAAAAAAAAgDa48fAtazcdufPUDABK5uYTx8+cfO
; +tq6cvv/vJrWcefnoGACVy1/efvvzgf/62sWj6z9KNawYAJZBuVfe99eqVnWE1N/136X8zA4Apuf3c
; Yxf3CqpF00/E9L912wIwOil41i+8+FGXsFr02Ks/+1ghD2A0UpmebkyrhtXibeu2R75+fgYAQ3L0/H
; Mf9g2qnab/Lz8RAWRn/lwhV1gtFvKePwDIxh3fffxS7qBSyAPIyrLnCrlNhbznDwBWJpXiYwXVbret
; GQAsI/0sy1msH+S25ScigD0Zqlg/yG1LIQ/gOnbbAZaiPSKATcYu1vtqjwg0TtcdYEk/ET1/ABqj7w
; 6wFO0RgUa45QsPnj3IDrCk25Y9IlAxJRfrfbVHBCqjtOcKubVHBCohWrHeV4U8EJh0cFM5HSl0cqiQ
; B4Ix1Q6wtNvWDEDZlLADLEV7RKBQai/W+2qPCBTG0B/Yq0F7RGBiouwAS9EeEZiIVp4r5FYhD4xI9B
; 1gKXr+AAxMLTvAUlTIAwNR4w6wFBXyQCYU6+OokAcOiGJ9XO0RgR60ugMsRYU80JHWd4Cl6AOBwBLs
; AMszPSHxExFYwA6wbH0gENjCDjCG6Sdi+lu5baFJPFeIaSrkPX9AU3iuEFt7RDRB+jmhWK9Hzx9QLY
; r1OrVHRHXYAdavPSLCo1hvS3tEhEWx3qb2iAiFD+wxqZBH8fjAHhe1R0SxKNa5l+kpi5+IKALPFdhF
; e0RMjmKdq6iQxySkf3CeK7CvCnmMhg/sMYf2iBgcO0DmNt22/EREVhTrHFJ7RGTDB/Y4lvaI6I0dIK
; fQHhEr47kCp1Qhj07YAbIkPX/AntgBskTtEXEddoAsXXtEeK7AUKZCPv0SmKE9FOuMqD1iY6Q/dCoz
; I/0jJXeqkG8AO0DWpOcPFWMHyFq1R6wIxTpb0B6xAuwA2ZIptOwRA2IHyJa1RwyE5wqkQr540jVYsU
; 5u1/OHAlGsk3urkC8IO0Cymwr5CVGsk6urkJ8AxTrZX3vEkfCBPTKfCvkBSaWhD+yRefWBwAHwXIEc
; Vh8IzIDnCuR4pkLe84ee2AGS46uQX5FUAnquQE6rQr4DPrBHlqM94j4o1sky9YHABRTrZPnaI26x/v
; L5qw/880+h/nhkaz7wrw827nn5/Cez1rn7+e9dvffnP9k49cE7of6AZCue+usfNu7+0Q82jjzzpMBK
; gbX+0xc2kifefn3jgX//JdQfk6zZ46+/snHXc89sKrBm2wMreezXFzZO//29UH9UsjbTreqel358La
; wE1hY7AyuZfiLe/8c33bbICbzv7de2BZXAWmC3wJp7/LVfbCjkyXFMxfr6hRd3DSuBtcV+gTW/bZ18
; /+1Qf3gymid+/9s9g0pgLbAssObe9+Zv/EQkBzD1xsvCSmBt0TWw5oW85w9kHlOxfvSFH3YKK4G1xS
; qBpZAn83j8dxc7B5XAWmDVwFos5D1/IFdzt+cKAmsF+gbW4m0r0j8Ycir3eq4gsFbgIIG17fmDn4jk
; rqbnCl2LdYG1hByBNb9tKeTJ7a5arAusJeQKrHV7RHKbiztAgZWJ3IE1f/6gkGerHqRYF1hLGCKwPH
; 9gqx60WBdYSxgqsLYV8vaIrNxUrN/7ykuDhZXA2mLowJrftuwRWasn/3xp8wN7Q4aVwNpijMCaa4/I
; 2sxdrAusJYwZWPNC3vMHRjfncwWBtQJjB9a6Qp7BHbJYF1hLmCKw5irkGcllH9gTWCMwZWAt3rYi/c
; Nle3b5wJ7AGoGpA2vbbctPRBZojh2gwMpEKYE1v20p5FmKUxTrAmsJJQXWXHtETm2fD+wJrBEoMbCS
; 9oicwqF2gAIrE6UG1vwnokKeYznVcwWBtQIlB9Zczx84pGPsAAVWJiIE1vy2ZY/I3I61AxRYmYgSWH
; PtEZnLMXeAAisT0QIrublH/LQcjXQ4WI6lPVcQWCsQMbCS9ojsY+nFusBaQtTAmquQZxen3gEKrExE
; D6z5bUshz70sYQcosDJRQ2Bdu2298Ss/EbnNUnaAAisTNQXW5m3rly/bIzJssS6wllBbYG2G1qc/EU
; +884bbVqOWuAMUWJmoMbDmpkLeHrEdS94BCqxM1BxY89uWPWL9Rn6uILBWoPbAWrxtef5Qn+m5Qk3F
; usBaQiuBNb9tKeTrscZiXWAtoaXAmusDgfGNtgMUWJloMbCSPhAY09qLdYG1hFYDK2mPGMsWinWBtY
; SWA2uuQr5so3xgT2CNgMD6/23LHrE8I31gT2CNgMDarg8ElmOLxbrAWoLAut7NDwR6/jCZrT1XEFgr
; ILB2VyE/jbXuAAVWJgTW/irkx/H0P95v9rmCwFoBgbVce8RhreUDewJrBARWdzdvW34iZrWVHaDAyo
; TAWk17xDwq1gVWLwRWP+0R++u5gsDqjcDqrz3iara8AxRYmRBYB9Pzh262vgMUWJkQWHn0/GF37QAF
; VlYEVj7tEbdrByiwsiOw8muPqFgXWAMhsIax1T2i5woCa1AE1nC2Vsgr1gXW4Ais4a29kE/F+vqFF0
; MdfoEVFIE1jrXuEe0ABdaoCKxxrWmPaAcosEZHYI1v9D2iYl1gTYbAms6Ie0Qf2BNYkyKwpjXKHtEO
; UGAVgcCa3tILec8VBFYxCKxyLO35Q3quoFgXWEUhsMqylEI+/QS0AxRYxSGwynTKQt4OUGAVi8Aq17
; ELecW6wCoegVW2Y+0RFesCKwQCK4ZDFfI+sCewQiGw4pj7A4H3v/uWYl1gxUJgxTPHBwI9VxBYIRFY
; Me37gUA7QIEVGoEV11ULeTtAgRUegRXfVMjv9/zBcwWBVQ0Cqw732iN6riCwqkJg1eX8A4F2gAKrSg
; RWfabblmJdYFWJwKrTSAeRAqszAqtOIx1ECqzOCKw6jXQQKbA6I7DqNNJBpMDqjMCq00gHkQKrMwKr
; TiMdRAqszgisOo10ECmwOiOw6jTSQaTA6ozAqtNIB5ECqzMCq04jHUQKrM4IrDqNdBApsDojsOo00k
; GkwOqMwKrTSAeRAqszAqtOIx1ECqzOCKw6jXQQKbA6I7DqNNJBpMDqjMCq00gHkQKrMwKrTiMdRAqs
; zgisOo10ECmwOiOw6jTSQaTA6ozAqtNIB5ECqzMCq04jHUQKrM4IrDqNdBApsDojsOo00kGkwOqMwK
; rTSAeRAqszAqtOIx1ECqzOCKw6jXQQKbA6I7DqNNJBpMDqjMCq00gHkQKrMwKrTiMdRAqszgisOo10
; ECmwOiOw6jTSQaTA6ozAqtNIB5ECqzMCq04jHUQKrM7cdOTOM0eefepKpMPI5UY6iFzu2hPnrtx0x9
; qZGf7Hbd/6xuVIB5ICqxVv/epXLs9wPem25SdiHUY6kNzd9BPwM0fvPjvD/tz+7Uc/jHQ4KbBq8/Zz
; j308Q3duPnX/00dfeP6TSIeUAqsGbz598vwMq5N+Iq49fu6jSAeVAiuq6ValWM9AKuTdtmIZ6aBSsZ
; 4dhXwsIx3WllWsD4xCPoaRDm2rKtZH4tCx9bN+IpZtpIPbom5VI5N+IrptlWukw9uS6VZ1462HT80w
; DYe//KWLblvlGekQt+Lhhx+6NMP0KOTLM9JBrt1UrHuuUCD2iOUY6UDX7Ge/+bUPZyiXdNvyE3F6Ix
; 3qWlWsB0IhP62RDnZteq4QFHvE6Yx0wGvyli9+/uIMcbFHnMZIh7wG7QArQyE/rpEOe3TtACvF84fx
; jHTgo2oH2AgK+eGNdPAjqlhvDIX8sEY6/NH0gb1GsUcUWJG0A8Qm9ogCq3TtALENhbzAKlHFOvbF8w
; eBVYp2gOiEPaLAmlq3KqzEDYcOrSnkBdbYKtZxIDx/EFhjaQeILNgjCqwhtQPEICjkBVZu7QAxKJ4/
; CKwceq6AUVHIC6y+2gFiEhTyAmtV7QAxKQp5gdVFxTqKIhXyblsCazcV6ygShbzAWlSxjhAo5AXW5x
; 595KMZEIVDx9bPtvwTMVK45NatCiFp+QOBkQIml3aAqIIWPxAYKWhyaAeIqmitkI8UNgfxjie/c9Vz
; BVRLK3vESKHTVx/YQxO08IHASMHTR8U6mqPmQj5S+KyiHSCaptY9YqQQ6qodIDCrc48YKYi63KoU68
; AOatojRgqk/bQDBPahlucPkUJpN+0AgRWIXshHCqedKtaBHkTeI0YKqEXdqoADEHWPGCmk5rcqO0Ag
; E9H2iJHC6vDDD12aAchLpEI+QlAp1oERiLBHLD2s7ACBESl9j1hyWLlVARNww6FDa6UW8iUGlWIdKI
; AS94ilhZUP7AEFUdoesZSgsgMECqaUQr6EsLIDBAJQwvOHKYPKcwUgIFMW8lOFlR0gEJipCvkpwsoH
; 9oAKmKKQH/tWpVgHKmPMPeJYYWUHCFTMWIX80EGlWAcaYuhCfsiwsgMEGmTIDwQOFVZuVUDDDPWBwN
; xBZQcI4Bq5C/mcYWUHCOA60m3ryLNPXSklsNaeOHfFcwUA+5Jjj3jQsLIDBNCZgz5/6BtUnisA6E3f
; Qr5vsT4DgIPQZ4+4aljZAQLIxqp7xFVuVYp1AIOQCvkuty3FOoAi6FLIK9YBFMV+hbxiHUBx7LVH3C
; 2s3KoATM5ue8Sdtyo7QABFsbhHnIeVD+wBKJZ5Ia9YBwAAAAAAAAAAAAAAAACgPP4Lq7YQRYhgCrMA
; AAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.60mm
; perimeters extrusion width = 0.66mm
; infill extrusion width = 0.66mm
; solid infill extrusion width = 0.72mm
; top infill extrusion width = 0.56mm
; first layer extrusion width = 0.72mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=simple-cube.stl_id_0_copy_0 CENTER=175,175 POLYGON=[[174.5,175.5],[174.5,174.5],[175.5,174.5],[175.5,175.5],[174.5,175.5]]
M106 S0
M106 P2 S0
;TYPE:Custom
START_PRINT EXTRUDER_TEMP=270 BED_TEMP=105 CHAMBER_TEMP=35 MATERIAL=ABS
M106 P3 S153
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
SET_PRESSURE_ADVANCE ADVANCE=0.03; Override pressure advance value
M106 S0
M106 P2 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-1 F1800
;AFTER_LAYER_CHANGE
;0.2
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=1500
G1 Z.6 F42000
G1 X171.603 Y171.233
G1 Z.6
G1 Z.2
G1 E1 F1800
;TYPE:Skirt
;WIDTH:0.72
G1 F2139
G1 X171.635 Y171.19 E.00297
G1 X173.267 Y170.301 E.10466
G1 X174.495 Y170.125 E.06981
G1 X175.505 Y170.125 E.0569
G1 X177.322 Y170.52 E.10466
G1 X178.81 Y171.635 E.10466
G1 X179.699 Y173.267 E.10466
G1 X179.875 Y174.495 E.06981
G1 X179.875 Y175.505 E.0569
G1 X179.48 Y177.322 E.10466
G1 X178.365 Y178.81 E.10466
G1 X176.733 Y179.699 E.10466
G1 X175.505 Y179.875 E.06981
G1 X174.495 Y179.875 E.0569
G1 X172.678 Y179.48 E.10466
G1 X171.19 Y178.365 E.10466
G1 X170.301 Y176.733 E.10466
G1 X170.125 Y175.505 E.06981
G1 X170.125 Y174.495 E.0569
G1 X170.52 Y172.678 E.10466
G1 X171.567 Y171.281 E.09831
G1 X172.116 Y171.742 F42000
G1 F2139
G1 X172.296 Y171.528 E.01577
G1 X174.495 Y170.802 E.13036
G1 X175.505 Y170.802 E.0569
G1 X177.166 Y171.197 E.09611
G1 X178.472 Y172.296 E.09611
G1 X179.198 Y174.495 E.13036
G1 X179.198 Y175.505 E.0569
G1 X178.803 Y177.166 E.09611
G1 X177.704 Y178.472 E.09611
G1 X175.505 Y179.198 E.13036
G1 X174.495 Y179.198 E.0569
G1 X172.834 Y178.803 E.09611
G1 X171.528 Y177.704 E.09611
G1 X170.802 Y175.505 E.13036
G1 X170.802 Y174.495 E.0569
G1 X171.197 Y172.834 E.09611
G1 X172.077 Y171.788 E.07696
G1 X172.581 Y172.282 F42000
G1 F2139
G1 X172.95 Y171.905 E.02969
G1 X174.495 Y171.479 E.09021
G1 X175.505 Y171.479 E.0569
G1 X176.995 Y171.872 E.08672
G1 X178.095 Y172.95 E.08672
G1 X178.521 Y174.495 E.09021
G1 X178.521 Y175.505 E.0569
G1 X178.128 Y176.995 E.08672
G1 X177.05 Y178.095 E.08672
G1 X175.505 Y178.521 E.09021
G1 X174.495 Y178.521 E.0569
G1 X173.005 Y178.128 E.08672
G1 X171.905 Y177.05 E.08672
G1 X171.479 Y175.505 E.09021
G1 X171.479 Y174.495 E.0569
G1 X171.872 Y173.005 E.08672
G1 X172.539 Y172.324 E.05365
G1 X172.972 Y172.849 F42000
G1 F2139
G1 X173.591 Y172.338 E.04518
G1 X174.495 Y172.156 E.0519
G1 X175.505 Y172.156 E.0569
G1 X176.801 Y172.548 E.07618
G1 X177.662 Y173.591 E.07618
G1 X177.844 Y174.495 E.0519
G1 X177.844 Y175.505 E.0569
G1 X177.452 Y176.801 E.07618
G1 X176.409 Y177.662 E.07618
G1 X175.505 Y177.844 E.0519
G1 X174.495 Y177.844 E.0569
G1 X173.199 Y177.452 E.07618
G1 X172.338 Y176.409 E.07618
G1 X172.156 Y175.505 E.0519
G1 X172.156 Y174.495 E.0569
G1 X172.548 Y173.199 E.07618
G1 X172.926 Y172.887 E.02762
; printing object simple-cube.stl id:0 copy 0
G1 E-.7 F1800
;WIPE_START
G1 F3000
G1 X173.591 Y172.338 E-.25874
G1 X173.726 Y172.311 E-.04126
;WIPE_END
EXCLUDE_OBJECT_START NAME=simple-cube.stl_id_0_copy_0
G1 Z.6 F42000
G1 X175.242 Y175 Z.6
G1 Z.2
G1 E1 F1800
;TYPE:Outer wall
;WIDTH:0.526816
G1 F2139
G1 X175.242 Y174.758 E.00974
G1 X174.758 Y174.758 E.01947
G1 X174.758 Y175.242 E.01947
G1 X175.242 Y175.242 E.01947
G1 X175.242 Y175 E.00974
; stop printing object simple-cube.stl id:0 copy 0
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G92 E0

G1 E-.7 F1800
;WIPE_START
G1 F6000
G1 X175.242 Y175.242 E-.07258
G1 X174.758 Y175.242 E-.14517
G1 X174.758 Y174.968 E-.08225
;WIPE_END
EXCLUDE_OBJECT_END NAME=simple-cube.stl_id_0_copy_0
;AFTER_LAYER_CHANGE
;0.4
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=25000 ACCEL_TO_DECEL=12500
M140 S100 ; set bed temperature
; printing object simple-cube.stl id:0 copy 0
SET_VELOCITY_LIMIT ACCEL=6000 ACCEL_TO_DECEL=3000
EXCLUDE_OBJECT_START NAME=simple-cube.stl_id_0_copy_0
G1 Z.8 F42000
G1 X175.242 Y175.242 Z.8
G1 Z.4
G1 E1 F1800
G1 F600
G1 X174.758 Y175.242 E.01947
G1 X174.758 Y174.758 E.01947
G1 X175.242 Y174.758 E.01947
G1 X175.242 Y175.182 E.01706
; stop printing object simple-cube.stl id:0 copy 0
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.6
G92 E0

G1 E-.85 F1800
;WIPE_START
G1 F12000
G1 X174.758 Y175.242 E-.07314
G1 X174.758 Y174.758 E-.07258
G1 X174.787 Y174.758 E-.00428
;WIPE_END
EXCLUDE_OBJECT_END NAME=simple-cube.stl_id_0_copy_0
;AFTER_LAYER_CHANGE
;0.6
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object simple-cube.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=simple-cube.stl_id_0_copy_0
G1 Z1 F42000
G1 X175.242 Y175.242 Z1
G1 Z.6
G1 E1 F1800
G1 F600
G1 X174.758 Y175.242 E.01947
G1 X174.758 Y174.758 E.01947
G1 X175.242 Y174.758 E.01947
G1 X175.242 Y175.182 E.01706
; stop printing object simple-cube.stl id:0 copy 0
M106 S153
M106 P2 S38
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.8
G92 E0

G1 E-.85 F1800
;WIPE_START
G1 F12000
G1 X174.758 Y175.242 E-.07314
G1 X174.758 Y174.758 E-.07258
G1 X174.787 Y174.758 E-.00428
;WIPE_END
EXCLUDE_OBJECT_END NAME=simple-cube.stl_id_0_copy_0
;AFTER_LAYER_CHANGE
;0.8
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object simple-cube.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=simple-cube.stl_id_0_copy_0
G1 Z1.2 F42000
G1 X175.242 Y175.242 Z1.2
G1 Z.8
G1 E1 F1800
G1 F600
G1 X174.758 Y175.242 E.01947
G1 X174.758 Y174.758 E.01947
G1 X175.242 Y174.758 E.01947
G1 X175.242 Y175.182 E.01706
; stop printing object simple-cube.stl id:0 copy 0
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;1
G92 E0

G1 E-.85 F1800
;WIPE_START
G1 F12000
G1 X174.758 Y175.242 E-.07314
G1 X174.758 Y174.758 E-.07258
G1 X174.787 Y174.758 E-.00428
;WIPE_END
EXCLUDE_OBJECT_END NAME=simple-cube.stl_id_0_copy_0
;AFTER_LAYER_CHANGE
;1
;_SET_FAN_SPEED_CHANGING_LAYER
; printing object simple-cube.stl id:0 copy 0
EXCLUDE_OBJECT_START NAME=simple-cube.stl_id_0_copy_0
G1 Z1.4 F42000
G1 X175.242 Y175.242 Z1.4
G1 Z1
G1 E1 F1800
G1 F600
G1 X174.758 Y175.242 E.01947
G1 X174.758 Y174.758 E.01947
G1 X175.242 Y174.758 E.01947
G1 X175.242 Y175.182 E.01706
; stop printing object simple-cube.stl id:0 copy 0
G1 E-.85 F1800
;WIPE_START
G1 F12000
G1 X174.758 Y175.242 E-.07314
G1 X174.758 Y174.758 E-.07258
G1 X174.787 Y174.758 E-.00428
;WIPE_END
EXCLUDE_OBJECT_END NAME=simple-cube.stl_id_0_copy_0
M106 S0
M106 P2 S0
;TYPE:Custom
; filament end gcode
END_PRINT
M106 P3 S255
; EXECUTABLE_BLOCK_END

; filament used [mm] = 5.97
; filament used [cm3] = 0.01
; filament used [g] = 0.01
; filament cost = 0.00
; total filament used [g] = 0.01
; total filament cost = 0.00
; total layers count = 5
; estimated printing time (normal mode) = 6s
; estimated first layer printing time (normal mode) = 0.795406s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 1
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 15
; align_infill_direction_to_model = 0
; alternate_extra_wall = 0
; auxiliary_fan = 1
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; bed_temperature_formula = by_highest_temp
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_density = 100%
; bottom_surface_pattern = monotonic
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_use_efc_outline = 0
; brim_width = 5
; calib_flowrate_topinfill_special_order = 0
; chamber_temperature = 35
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 3
; complete_print_exhaust_fan_speed = 100
; cool_plate_temp = 0
; cool_plate_temp_initial_layer = 0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 25000
; default_bed_type = 
; default_filament_colour = ""
; default_filament_profile = "Generic PLA @System"
; default_jerk = 0
; default_junction_deviation = 0
; default_nozzle_volume_type = Standard
; default_print_profile = 0.20mm Standard @MyKlipper
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 0
; different_settings_to_system = brim_type;default_acceleration;gap_infill_speed;infill_direction;initial_layer_acceleration;initial_layer_infill_speed;initial_layer_speed;inner_wall_acceleration;inner_wall_speed;internal_bridge_speed;internal_solid_infill_speed;only_one_wall_first_layer;outer_wall_acceleration;outer_wall_speed;skirt_height;skirt_loops;small_perimeter_speed;small_perimeter_threshold;sparse_infill_speed;top_surface_acceleration;top_surface_speed;travel_acceleration;travel_speed;wall_sequence;activate_air_filtration;additional_cooling_fan_speed;chamber_temperature;compatible_printers;complete_print_exhaust_fan_speed;during_print_exhaust_fan_speed;enable_pressure_advance;fan_max_speed;fan_min_speed;filament_flow_ratio;filament_max_volumetric_speed;filament_shrink;nozzle_temperature;nozzle_temperature_initial_layer;pressure_advance;auxiliary_fan;disable_m73;machine_end_gcode;machine_max_acceleration_extruding;machine_max_acceleration_x;machine_max_acceleration_y;machine_max_jerk_e;machine_max_jerk_x;machine_max_jerk_y;machine_max_jerk_z;machine_max_speed_x;machine_max_speed_y;machine_max_speed_z;machine_start_gcode;nozzle_type;print_host;printable_area;printable_height;retraction_length
; disable_m73 = 1
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_extra_bridge_layer = disabled
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_power_loss_recovery = printer_configuration
; enable_pressure_advance = 1
; enable_prime_tower = 0
; enable_support = 0
; enable_tower_interface_cooldown_during_tower = 0
; enable_tower_interface_features = 0
; enable_wrapping_detection = 0
; enforce_support_layers = 0
; eng_plate_temp = 100
; eng_plate_temp_initial_layer = 105
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extra_solid_infills = 
; extruder_ams_count = 1#0|4#0;1#0|4#0
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A
; extruder_offset = 0x0
; extruder_printable_area = 
; extruder_printable_height = 0
; extruder_type = Direct Drive
; extruder_variant_list = "Direct Drive Standard"
; extrusion_rate_smoothing_external_perimeter_only = 0
; fan_cooling_layer_time = 30
; fan_kickstart = 0
; fan_max_speed = 60
; fan_min_speed = 30
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_adaptive_volumetric_speed = 0
; filament_adhesiveness_category = 0
; filament_change_length = 10
; filament_colour = #26A69A
; filament_colour_type = 1
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.04
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode\n"
; filament_extruder_variant = "Direct Drive Standard"
; filament_flow_ratio = 1
; filament_flush_temp = 0
; filament_flush_volumetric_speed = 0
; filament_ids = OGFB99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_map = 1
; filament_map_mode = Auto For Flush
; filament_max_volumetric_speed = 34
; filament_minimal_purge_on_wipe_tower = 15
; filament_multi_colour = #26A69A
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_printable = 3
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_self_index = 1
; filament_settings_id = "eSUN ABS HS"
; filament_shrink = 98.94%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; Filament gcode\n"
; filament_toolchange_delay = 0
; filament_tower_interface_pre_extrusion_dist = 10
; filament_tower_interface_pre_extrusion_length = 0
; filament_tower_interface_print_temp = -1
; filament_tower_interface_purge_volume = 20
; filament_tower_ironing_area = 4
; filament_type = ABS
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; file_start_gcode = 
; filename_format = {input_filename_base}_{layer_height}mm_{filament_type[initial_tool]}_{printer_model}_{print_time}.gcode
; fill_multiline = 1
; filter_out_gap_fill = 0
; first_layer_flow_ratio = 1
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = disabled_fuzzy
; fuzzy_skin_first_layer = 0
; fuzzy_skin_mode = displacement
; fuzzy_skin_noise_type = classic
; fuzzy_skin_octaves = 4
; fuzzy_skin_persistence = 0.5
; fuzzy_skin_point_distance = 0.3
; fuzzy_skin_scale = 1
; fuzzy_skin_thickness = 0.2
; gap_fill_flow_ratio = 1
; gap_fill_target = nowhere
; gap_infill_speed = 120
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; grab_length = 0
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 100
; hot_plate_temp_initial_layer = 105
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 0
; infill_jerk = 9
; infill_lock_depth = 1
; infill_overhang_angle = 60
; infill_shift_step = 0.4
; infill_wall_overlap = 25%
; inherits_group = "0.20mm Standard @MyKlipper";"Generic ABS @System";"MyKlipper 0.6 nozzle"
; initial_layer_acceleration = 3000
; initial_layer_infill_speed = 200
; initial_layer_jerk = 9
; initial_layer_line_width = 120%
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 100
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 25000
; inner_wall_flow_ratio = 1
; inner_wall_jerk = 9
; inner_wall_line_width = 110%
; inner_wall_speed = 400
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_angle = 0
; internal_bridge_density = 100%
; internal_bridge_fan_speed = -1
; internal_bridge_flow = 1
; internal_bridge_speed = 300%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_flow_ratio = 1
; internal_solid_infill_line_width = 120%
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 400
; ironing_angle = 0
; ironing_angle_fixed = 0
; ironing_fan_speed = -1
; ironing_flow = 10%
; ironing_inset = 0
; ironing_pattern = rectilinear
; ironing_spacing = 0.15
; ironing_speed = 30
; ironing_type = no ironing
; is_infill_first = 0
; lateral_lattice_angle_1 = -45
; lateral_lattice_angle_2 = 45
; layer_change_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; line_width = 110%
; long_retractions_when_cut = 0
; long_retractions_when_ec = 0
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 30000,20000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 20000,20000
; machine_max_acceleration_x = 30000,20000
; machine_max_acceleration_y = 30000,20000
; machine_max_acceleration_z = 500,200
; machine_max_jerk_e = 0,2.5
; machine_max_jerk_x = 0,9
; machine_max_jerk_y = 0,9
; machine_max_jerk_z = 0,0.4
; machine_max_junction_deviation = 0.01
; machine_max_speed_e = 25,25
; machine_max_speed_x = 600,200
; machine_max_speed_y = 600,200
; machine_max_speed_z = 60,12
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = START_PRINT EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single] CHAMBER_TEMP=[chamber_temperature] MATERIAL=[filament_type]
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; master_extruder_id = 1
; max_bridge_length = 10
; max_layer_height = 0.4
; max_resonance_avoidance_speed = 120
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.12
; min_length_factor = 0.5
; min_resonance_avoidance_speed = 70
; min_skirt_length = 4
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 15
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.6
; nozzle_flush_dataset = 0
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 270
; nozzle_temperature_initial_layer = 270
; nozzle_temperature_range_high = 280
; nozzle_temperature_range_low = 240
; nozzle_type = tungsten_carbide
; nozzle_volume = 0
; nozzle_volume_type = Standard
; only_one_wall_first_layer = 1
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 6000
; outer_wall_flow_ratio = 1
; outer_wall_jerk = 9
; outer_wall_line_width = 100%
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 80
; overhang_fan_threshold = 25%
; overhang_flow_ratio = 1
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; physical_extruder_map = 0
; post_process = 
; precise_outer_wall = 1
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.03
; prime_tower_brim_width = 3
; prime_tower_enable_framework = 0
; prime_tower_flat_ironing = 0
; prime_tower_infill_gap = 150%
; prime_tower_skip_points = 1
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "MyKlipper 0.4 nozzle";"MyKlipper 0.6 nozzle";"MyKlipper 0.8 nozzle"
; print_extruder_id = 1
; print_extruder_variant = "Direct Drive Standard"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Darky
; printable_area = 0x0,350x0,350x350,0x350
; printable_height = 350
; printer_agent = 
; printer_extruder_id = 1
; printer_extruder_variant = "Direct Drive Standard"
; printer_model = Generic Klipper Printer
; printer_notes = 
; printer_settings_id = Darky
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.6
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 3
; resolution = 0.012
; resonance_avoidance = 0
; retract_before_wipe = 70%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_distances_when_ec = 10
; retraction_length = 1
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; set_other_flow_ratios = 0
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; single_loop_draft_shield = 0
; skeleton_infill_density = 25%
; skeleton_infill_line_width = 100%
; skin_infill_density = 25%
; skin_infill_depth = 2
; skin_infill_line_width = 100%
; skirt_distance = 2
; skirt_height = 1
; skirt_loops = 1
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 3
; slow_down_layers = 0
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 100%
; small_perimeter_threshold = 6.5
; solid_infill_direction = 45
; solid_infill_filament = 1
; solid_infill_rotate_template = 
; sparse_infill_acceleration = 100%
; sparse_infill_density = 15%
; sparse_infill_filament = 1
; sparse_infill_flow_ratio = 1
; sparse_infill_line_width = 110%
; sparse_infill_pattern = crosshatch
; sparse_infill_rotate_template = 
; sparse_infill_speed = 450
; spiral_finishing_flow_ratio = 0
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; spiral_starting_flow_ratio = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; supertack_plate_temp = 0
; supertack_plate_temp_initial_layer = 0
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = default
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_flow_ratio = 1
; support_interface_bottom_layers = 2
; support_interface_filament = 0
; support_interface_flow_ratio = 1
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_ironing = 0
; support_ironing_flow = 10%
; support_ironing_pattern = rectilinear
; support_ironing_spacing = 0.1
; support_line_width = 96%
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_first_layer_gap = 0.2
; support_object_skip_flush = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 150
; support_style = default
; support_threshold_angle = 30
; support_threshold_overlap = 50%
; support_top_z_distance = 0.2
; support_type = normal(auto)
; symmetric_infill_y_axis = 0
; temperature_vitrification = 110
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 100
; textured_plate_temp_initial_layer = 105
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 48x48/PNG,300x300/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 12000
; top_surface_density = 100%
; top_surface_jerk = 9
; top_surface_line_width = 93.75%
; top_surface_pattern = monotonicline
; top_surface_speed = 250
; travel_acceleration = 25000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 700
; travel_speed_z = 0
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 30
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; volumetric_speed_coefficients = ""
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = arachne
; wall_loops = 3
; wall_sequence = inner-outer-inner wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 30
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_rib_length = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_fillet_wall = 1
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rib_width = 8
; wipe_tower_rotation_angle = 0
; wipe_tower_type = type2
; wipe_tower_wall_type = rectangle
; wipe_tower_x = -64.000
; wipe_tower_x = -64
; wipe_tower_y = -9.625
; wipe_tower_y = -9.625
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; wrapping_detection_gcode = 
; wrapping_detection_layers = 20
; wrapping_exclude_area = 
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 105
; bed_shape = 0x0,350x0,350x350,0x350
; first_layer_temperature = 270
; first_layer_height = 0.200
; CONFIG_BLOCK_END


