//! G-code generation from sliced layers.
//!
//! Converts a `Vec<SliceLayer>` and a `SlicingParams` into a G-code string
//! suitable for FFF (fused-filament fabrication) printers.
//!
//! This is a *rough first-draft* implementation that covers the core workflow:
//! start-up, per-layer contour printing, and shut-down.  Advanced features
//! (infill, supports, variable speed, retraction tuning) are deferred.

use crate::core::SliceLayer;
use crate::settings::params::SlicingParams;

/// Default filament diameter in mm (standard 1.75 mm PLA/PETG/etc.).
const FILAMENT_DIAMETER_MM: f64 = 1.75;

/// Default nozzle diameter in mm.
const NOZZLE_DIAMETER_MM: f64 = 0.4;

/// Travel (non-print) speed in mm/min.
const TRAVEL_SPEED_MM_MIN: f64 = 9000.0;

/// Z-hop height above the current layer during travel moves (mm).
const Z_HOP_MM: f64 = 0.2;

/// Retraction distance on travel moves (mm).
const RETRACT_MM: f64 = 1.0;

/// Compute the extrusion length (mm of filament) needed to print a straight
/// line of length `move_len` at the given `layer_height` with the default
/// nozzle and filament diameters.
///
/// Formula: E = line_length × (layer_height × nozzle_diameter) / (π × filament_radius²)
fn extrusion_for_move(move_len: f64, layer_height: f64) -> f64 {
    let filament_radius = FILAMENT_DIAMETER_MM / 2.0;
    let cross_section = layer_height * NOZZLE_DIAMETER_MM;
    let filament_area = std::f64::consts::PI * filament_radius.powi(2);
    move_len * cross_section / filament_area
}

/// Generate a G-code string from a slice result.
///
/// The returned string is ready to be written directly to a `.gcode` file.
///
/// # Arguments
/// * `layers` – ordered bottom-to-top slice layers produced by [`crate::core::slice_mesh`]
/// * `params` – slicing parameters (temperatures, speeds, layer height, …)
///
/// # Returns
/// A `String` containing the full G-code program.  Returns a minimal
/// (start + end only) program when `layers` is empty.
///
/// # Example
/// ```
/// use slicer_engine::gcode::generate_gcode;
/// use slicer_engine::settings::params::SlicingParams;
///
/// let gcode = generate_gcode(&[], &SlicingParams::default());
/// assert!(gcode.contains("G28"));
/// assert!(gcode.contains("M104 S0"));
/// ```
pub fn generate_gcode(layers: &[SliceLayer], params: &SlicingParams) -> String {
    let mut out = String::with_capacity(64 * 1024);
    let print_speed_mm_min = params.print_speed * 60.0;

    // ── Start sequence ───────────────────────────────────────────────────────
    out.push_str("; Generated by slicer-engine\n");
    out.push_str("G21 ; millimetres\n");
    out.push_str("G90 ; absolute positioning\n");
    out.push_str("M82 ; extruder absolute mode\n");
    out.push_str(&format!(
        "M104 S{:.0} ; set nozzle temperature\n",
        params.nozzle_temp
    ));
    out.push_str(&format!(
        "M140 S{:.0} ; set bed temperature\n",
        params.bed_temp
    ));
    out.push_str("G28 ; home all axes\n");
    out.push_str(&format!(
        "M109 S{:.0} ; wait for nozzle temperature\n",
        params.nozzle_temp
    ));
    out.push_str(&format!(
        "M190 S{:.0} ; wait for bed temperature\n",
        params.bed_temp
    ));
    out.push_str("G92 E0 ; reset extruder\n");

    // ── Per-layer contours ───────────────────────────────────────────────────
    let mut e_total = 0.0_f64;

    for layer in layers {
        out.push_str(&format!("; layer z={:.3}\n", layer.z));
        out.push_str(&format!("G1 Z{:.3} F{:.0}\n", layer.z, TRAVEL_SPEED_MM_MIN));

        for path in layer.paths.iter() {
            let points: Vec<(f64, f64)> = path.iter().map(|p| (p.x(), p.y())).collect();
            if points.len() < 2 {
                continue;
            }

            let (start_x, start_y) = points[0];

            // Retract, hop, travel to start of contour
            e_total -= RETRACT_MM;
            out.push_str(&format!("G1 E{:.5} F3000 ; retract\n", e_total));
            out.push_str(&format!(
                "G1 Z{:.3} F{:.0} ; z-hop\n",
                layer.z + Z_HOP_MM,
                TRAVEL_SPEED_MM_MIN
            ));
            out.push_str(&format!(
                "G1 X{:.3} Y{:.3} F{:.0} ; travel\n",
                start_x, start_y, TRAVEL_SPEED_MM_MIN
            ));
            out.push_str(&format!(
                "G1 Z{:.3} F{:.0} ; lower\n",
                layer.z, TRAVEL_SPEED_MM_MIN
            ));
            // Un-retract
            e_total += RETRACT_MM;
            out.push_str(&format!("G1 E{:.5} F3000 ; un-retract\n", e_total));

            // Print the contour
            let mut prev = points[0];
            for &(x, y) in points.iter().skip(1) {
                let dx = x - prev.0;
                let dy = y - prev.1;
                let len = (dx * dx + dy * dy).sqrt();
                if len < 1e-6 {
                    prev = (x, y);
                    continue;
                }
                e_total += extrusion_for_move(len, params.layer_height);
                out.push_str(&format!(
                    "G1 X{:.3} Y{:.3} E{:.5} F{:.0}\n",
                    x, y, e_total, print_speed_mm_min
                ));
                prev = (x, y);
            }

            // Close the contour back to start
            let dx = start_x - prev.0;
            let dy = start_y - prev.1;
            let len = (dx * dx + dy * dy).sqrt();
            if len >= 1e-6 {
                e_total += extrusion_for_move(len, params.layer_height);
                out.push_str(&format!(
                    "G1 X{:.3} Y{:.3} E{:.5} F{:.0} ; close contour\n",
                    start_x, start_y, e_total, print_speed_mm_min
                ));
            }
        }
    }

    // ── End sequence ─────────────────────────────────────────────────────────
    out.push_str("; end of print\n");
    out.push_str("G91 ; relative positioning\n");
    out.push_str("G1 E-2 F3000 ; final retract\n");
    out.push_str("G1 Z5 F3000 ; lift nozzle\n");
    out.push_str("G90 ; absolute positioning\n");
    out.push_str("G28 X0 Y0 ; park\n");
    out.push_str("M104 S0 ; nozzle off\n");
    out.push_str("M140 S0 ; bed off\n");
    out.push_str("M84 ; disable motors\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::SliceLayer;

    #[test]
    fn test_generate_gcode_empty_layers_contains_header() {
        let gcode = generate_gcode(&[], &SlicingParams::default());
        assert!(gcode.contains("G28"), "missing G28 home");
        assert!(gcode.contains("G21"), "missing G21 mm mode");
        assert!(gcode.contains("M104 S210"), "missing nozzle temp");
        assert!(gcode.contains("M140 S60"), "missing bed temp");
    }

    #[test]
    fn test_generate_gcode_empty_layers_contains_footer() {
        let gcode = generate_gcode(&[], &SlicingParams::default());
        assert!(gcode.contains("M104 S0"), "missing nozzle off");
        assert!(gcode.contains("M140 S0"), "missing bed off");
        assert!(gcode.contains("M84"), "missing motors off");
    }

    #[test]
    fn test_generate_gcode_layer_z_appears() {
        let layer = SliceLayer::new(1.0);
        let gcode = generate_gcode(&[layer], &SlicingParams::default());
        assert!(
            gcode.contains("layer z=1.000"),
            "missing layer comment: {gcode}"
        );
        assert!(gcode.contains("G1 Z1.000"), "missing Z move");
    }

    #[test]
    fn test_generate_gcode_with_contour() {
        use clipper2::Path;
        let mut layer = SliceLayer::new(0.2);
        let square: Path = vec![(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0)].into();
        layer.paths.push(square);

        let gcode = generate_gcode(&[layer], &SlicingParams::default());
        // Should have at least one extrusion move
        assert!(gcode.contains(" E"), "no extrusion moves in gcode");
        // Travel move to the start point
        assert!(gcode.contains("X0.000 Y0.000"), "missing start travel");
    }

    #[test]
    fn test_extrusion_for_move_positive() {
        let e = extrusion_for_move(10.0, 0.2);
        assert!(e > 0.0, "extrusion must be positive");
    }
}
